# Generated by Django 5.0 on 2023-12-07 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('designation', models.CharField(choices=[('hr', 'hr'), ('back-end developer', 'back-end developer'), ('front-end developer', 'front-end developer'), ('fullstack developer', 'fullstack developer')], max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('jobmethod', models.CharField(choices=[('office', 'office'), ('wfh', 'wfh'), ('hybrid', 'hybrid')], default='office', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendancestatus', models.BooleanField(default=False)),
                ('login_time', models.TimeField()),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
